server:
  port: 8010
spring:
  application:
    name: provider #当前服务注册在 Eureka Server 上的名称 即该微服务的名字
eureka:
  client:
    #register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册中⼼的访问地址
    instance:
      prefer-ip-address: true #是否将当前服务的 IP 注册到 Eureka Server
      lease-renewal-interval-in-seconds: 1
      lease-expiration-duration-in-seconds: 2