server:
  port: 8761  #当前eureka server的服务端口

eureka:
  client:
    register-with-eureka: false  #是否将当前的eureka server服务作为客户端进行注册，一般选择false不注册
    fetch-registry: false  #是否获取其他eureka server服务的数据
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册中心的访问路径
  server:
    enable-self-preservation: false   #关闭自我保护,关闭后，当有微服务down后，状态会改变